### ISSUE TITLE
Tutorial doesn't show up for the first player.

### ISSUE THREAD

**Issue by bukaaa** [eharris93/ELB#94]
It seems like on the second player's turn there is a "welcome" tutorial, and it's missing when you first start the game. Tutorial shows up only when you interacted with something (e.g. moved to a tile, picked up a card).

**Comment by alasdairhurst** [comment]
#

**Comment by alasdairhurst** [comment]
#

**Comment by alasdairhurst** [comment]
#

**Comment by alasdairhurst** [comment]
#

**Comment by alasdairhurst** [comment]
#
